[package]
name = "query"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies.derive_more]
version = "2.1.1"
features = ["constructor"]

[dependencies.lazy-regex]
version = "3.5.0"

[dev-dependencies.pretty_assertions]
version = "1.4.1"
