name: Build image
on:
  pull_request:
  workflow_call:
    inputs:
      push:
        type: boolean
        default: false
      set:
        type: string
    outputs:
      version:
        value: ${{ jobs.image.outputs.version }}

defaults:
  run:
    shell: bash

jobs:
  image:
    name: ${{ matrix.target }} (${{ matrix.platform.os }}/${{ matrix.platform.arch }})
    runs-on: ${{ matrix.platform.label }}
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - api
          - ui
        platform:
          - os: linux
            arch: amd64
            label: ubuntu-24.04
          - os: linux
            arch: arm64
            label: ubuntu-24.04-arm
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Rust
        if: ${{ matrix.target == 'api' }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-src-dir: api
      - name: Set up cargo-edit
        if: ${{ matrix.target == 'api' }}
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: cargo-edit
          features: set-version
          no-default-features: true
      - name: Set up Node.js
        if: ${{ matrix.target == 'ui' }}
        uses: actions/setup-node@v6
        with:
          node-version-file: ui/.node-version
      - name: Install corepack
        if: ${{ matrix.target == 'ui' }}
        working-directory: ui
        run: |
          npm install -g -f corepack
          corepack enable
      - name: Get version
        uses: chitoku-k/actions/describe-git-tag@master
        id: version
        with:
          semantic-versioning: true
      - name: Set api version
        if: ${{ matrix.target == 'api' }}
        working-directory: api
        run: |
          cargo set-version ${{ steps.version.outputs.value }} --package=hoarder
      - name: Set ui version
        if: ${{ matrix.target == 'ui' }}
        working-directory: ui
        run: |
          yarn version ${{ steps.version.outputs.value }}
      - name: Log into Container Registry
        if: ${{ inputs.push || false }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build
        uses: docker/bake-action@v6
        id: build
        with:
          source: .
          targets: ${{ matrix.target }}
          set: |
            ${{ matrix.target }}.tags=ghcr.io/${{ github.repository }}/${{ matrix.target }}
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            *.output=type=image,push=${{ inputs.push || false }},push-by-digest=${{ inputs.push || false }}
            *.annotations=org.opencontainers.image.source=${{ github.repositoryUrl }}
            *.annotations=org.opencontainers.image.revision=${{ github.sha }}
            *.annotations=org.opencontainers.image.version=v${{ steps.version.outputs.value }}
            ${{ inputs.set }}
      - name: Upload digest
        if: ${{ inputs.push || false }}
        uses: chitoku-k/actions/upload-image-digest@master
        with:
          digest: ${{ fromJSON(steps.build.outputs.metadata)[matrix.target]['containerimage.digest'] }}
          artifact: digests-${{ matrix.target }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
